# The Numpy Library
## Introduction


In [1]:
import numpy as np
a= np.array([1,2,3])
print(a)

[1 2 3]


- np.linspace(startingno,endingno,interval)
- np.arange(staringno,finishno)
- np.random.random((row,column)) #note its from the np.random library
``` python
 '''Examples
import numpy as np
 a = np.linspace(1,50, 10)
 b = arange(12,50)
 np.random.random((4,4))'''


```

In [2]:
 # Examples
import numpy as np
 a =np.linspace(17,50, 10)
 print(a)
 b= np.arange(12,50)
print(b)
 np.random.random((4,4))
a+2
a-2
a*2


[17.         20.66666667 24.33333333 28.         31.66666667 35.33333333
 39.         42.66666667 46.33333333 50.        ]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([ 34.        ,  41.33333333,  48.66666667,  56.        ,
        63.33333333,  70.66666667,  78.        ,  85.33333333,
        92.66666667, 100.        ])

# Common functions
- a.min()  to get the minimum value
- a.max() to get max value in the array
- a.mean() to get the mean value in the array 
- a.std() to get the standard deviation of values in the array 
 # Matrix and Dot product functions

- np.dot(nparray1 , nparrray2) same as writing nprray1.dot(nparray2)
``` python
# Increment & Decrement
a = np.array([1,2,3],[4,5,6])
a += 1 #Incrementing

```

# Indexing 
starts from 0
use 
``` python

array.flat # to get a linear array
# used in cases of iterating 
one can use boolean
 ```



In [3]:
import numpy as np
a =np.random.random((3,4))
print(a < 0.5)
print(0.5 <a)

print(a)
a = a.ravel() # used to reverse a shape operation
print(a)
a = a.reshape(3,4)
print("normall array")
print(a)
print("Transposed array")
print(a.transpose())# Perform the inversion of columns with rows 


[[False False False False]
 [ True  True  True  True]
 [ True False False  True]]
[[ True  True  True  True]
 [False False False False]
 [False  True  True False]]
[[0.64520663 0.59081623 0.89253805 0.51546737]
 [0.07762695 0.07387389 0.19558541 0.09538583]
 [0.34296883 0.94072745 0.59881169 0.16044198]]
[0.64520663 0.59081623 0.89253805 0.51546737 0.07762695 0.07387389
 0.19558541 0.09538583 0.34296883 0.94072745 0.59881169 0.16044198]
normall array
[[0.64520663 0.59081623 0.89253805 0.51546737]
 [0.07762695 0.07387389 0.19558541 0.09538583]
 [0.34296883 0.94072745 0.59881169 0.16044198]]
Transposed array
[[0.64520663 0.07762695 0.34296883]
 [0.59081623 0.07387389 0.94072745]
 [0.89253805 0.19558541 0.59881169]
 [0.51546737 0.09538583 0.16044198]]


# Array Manipulation 
1. Joining arrays
- done using the vstack() function for vertical joining and hstack for horizontal joining 
``` python
a = np.zeros((3,3))
b = np.ones((3.3))
np.vstack((a,b))
np.hstack((a,b))

```
Or using colunm_stack() and row_stack() 
``` python

a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
 np.column_stack((a, b, c))
''' array([[0, 3, 6],
 [1, 4, 7],
 [2, 5, 8]])
'''
 np.row_stack((a, b, c))
''' array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])
 '''

```

2. Splitting Arrays 
- done using functions such as hsplit(Array, howmanytimes) for horizontal split use vsplit for vertical

``` python
a = np.arange(16).reshape((4,4))
[b,c]=vsplit(a ,2)
#using the split() fxn

[a,b,c] = np.split(Arraytobesplit,[1,3'''canbe anyshape'''],axis =1'''1 for column and 0 for row''')


```

In [7]:
a=np.array([1,2,3,4])
b=a
print(a)
a[0]=5
print(b)
#assigning a  value to an array when original value is changed the subsequent values
# but copy fxn changes this properties
b = a.copy()
a[0]=0
print(b)
print(a)


[1 2 3 4]
[5 2 3 4]
[5 2 3 4]
[0 2 3 4]


# Vectorization 
- Property of the numpy lubrary to avoid exlicit declaration of basic functions to act on arrays 
>For example
``` python
a = np.array([1,2,3,4],[5,6,7,8])
b = np.random.random([2,4])
# Due to vectorization we can achieve a mtrix product ie 
c = a * b
 # in other programming languages in involves nested for loops as seen below.

```

``` cpp
// This is in C++
for(i = 0 ; i < rows ; i++)
{
    c[i] =a[i] * b[i];
}

```

# Broadcasting 
- Property of numpy array that allows an operator to act on arrays that are not of same shape.But the arrays must meet certain rules  

In [9]:
a = np.arange(16).reshape(4,4)
b=np.arange(4)
print(a)
print(b)
print(a+b)
# the arrays to add up the b array undergo extension this is known as broadcasting


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]]


## Structured Arrays
> Contain structs and Records instead of individual items

In [13]:
structured = np.array([(1, 'First',0.5 ,1+2j),(2 ,'Second',1.3 ,2-2j),(2,'Third',0.8, 1+3j)],dtype=('i2,a6,f4,c8'))
print(structured)

[(1, b'First', 0.5, 1.+2.j) (2, b'Second', 1.3, 2.-2.j)
 (2, b'Third', 0.8, 1.+3.j)]


In [20]:
data =np.array([[ 0.86466285, 0.76943895, 0.22678279],
 [ 0.12452825, 0.54751384, 0.06499123],
 [ 0.06216566, 0.85045125, 0.92093862],
 [ 0.58401239, 0.93455057, 0.28972379]])
np.save('test',data)
loaded_data = np.load('test.npy')
print(loaded_data)

[[0.86466285 0.76943895 0.22678279]
 [0.12452825 0.54751384 0.06499123]
 [0.06216566 0.85045125 0.92093862]
 [0.58401239 0.93455057 0.28972379]]
